kind: Secret
apiVersion: v1
metadata:
  labels:
    app.kubernetes.io/component: grafana
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 7.4.3
  name: grafana-datasources
  namespace: default
stringData:
  datasources.yaml: |
    {
      "apiVersion": 1,
      "datasources": [
        {
          "access": "proxy",
          "editable": false,
          "name": "prometheus",
          "orgId": 1,
          "type": "prometheus",
          "url": "http://prometheus.default.svc",
          "version": 1
        }
      ]
    }
