apiVersion: v1
kind: Endpoints
metadata:
  name: database
  namespace: default
subsets:
  - addresses:
      - ip: 10.211.55.16
    ports:
      - name: metrics
        port: 9090
        protocol: TCP
