apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: metric-router
  namespace: default
  labels:
    app: prometheus
spec:
  selector:
    matchLabels:
      metric-router: active
  endpoints:
    - port: metrics
      path: /metrics/router
