apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: node
  namespace: default
  labels:
    app: prometheus
spec:
  selector:
    matchLabels:
      metric-node: active
  endpoints:
    - port: metrics
      path: /metrics/node
