# This is a patched CoreDNS configmap
# to support external server names
#
#

kind: ConfigMap
apiVersion: v1
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
        errors
        health {
           lameduck 5s
        }

        ready

        hosts /etc/coredns/hosts {
           fallthrough
        }

        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           fallthrough in-addr.arpa ip6.arpa
           ttl 30
        }
        prometheus :9153
        forward . /etc/resolv.conf {
           max_concurrent 1000
        }

        cache 30
        loop
        reload
        loadbalance
    }
  hosts: |
    10.211.55.15 monitor.server
    10.211.55.16 database.server
    10.211.55.17 web.server
